In [1]:
# Standard library imports
import os

# Third party library imports
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


In [2]:
# Reading the csv file

FILE_PATH = "../datasets/TASK_2/TASK_2/train_set.csv"
train_data = pd.read_csv(FILE_PATH)

In [3]:
train_data['CLASS'].value_counts().reset_index()

CLASS  count
0      0    191
1      1    124

In [5]:
y.isna().sum()

np.int64(0)

In [6]:
X = train_data.drop(columns=["ID", "CLASS"])
y = train_data["CLASS"]

In [7]:
missing_per_row = X.isnull().sum(axis=1)
missing_per_row.value_counts()


0     199
23    116
Name: count, dtype: int64

In [8]:
import numpy as np

# Count infinities
np.isinf(X.to_numpy()).sum()


np.int64(4)

In [9]:
inf_mask = np.isinf(X)
inf_summary = inf_mask.sum(axis=0)
inf_summary[inf_summary > 0]

Feature_72    2
Feature_90    2
dtype: int64

In [10]:
X_clean = X.replace([np.inf, -np.inf], np.nan)

In [12]:
X.iloc[50].isnull().value_counts().reset_index()

50  count
0  False   3215
1   True     23

In [13]:
from sklearn.impute import SimpleImputer

imputer = SimpleImputer(missing_values=np.nan, strategy="mean")
X_imputed = imputer.fit_transform(X_clean)

In [15]:
from sklearn.preprocessing import StandardScaler

scalar = StandardScaler()
X_scaled = scalar.fit_transform(X_imputed)

In [16]:
scalar.mean_, scalar.var_

(array([3.64016118e+04, 3.65589788e+04, 1.34217979e+04, ...,
        2.85106703e+01, 3.79238104e+00, 1.12015343e-01], shape=(3238,)),
 array([5.73178001e+08, 5.74492580e+08, 2.72592504e+07, ...,
        2.91915412e+00, 6.61509292e-02, 1.89172126e-03], shape=(3238,)))

In [17]:
X_scaled_df = pd.DataFrame(X_scaled, columns=X.columns)
X_scaled_df

Feature_1  Feature_2  Feature_3  Feature_4  Feature_5  Feature_6  \
0    -0.756859  -0.756281  -0.768458   1.790937  -0.703377  -0.622357   
1    -0.684660  -0.686690  -0.980408   0.279318   0.567037   0.393269   
2    -0.381832  -0.380581  -0.235997   0.738313  -0.658969  -0.592319   
3     0.231255   0.232764   0.851293   0.408853  -1.186714  -0.927422   
4     0.203521   0.203601   0.171085  -0.825213   0.093786  -0.031715   
..         ...        ...        ...        ...        ...        ...   
310   0.433827   0.435696   0.886849  -0.217469  -0.847973  -0.717820   
311  -1.168752  -1.170949  -1.748648   1.717631   1.244825   1.018591   
312   0.035969   0.035381   0.101320  -0.395710  -0.196988  -0.259780   
313  -0.472817  -0.471784  -0.331835   1.032608  -0.739118  -0.646287   
314   0.690171   0.691657   1.219785  -0.402856  -0.902918  -0.753154   

     Feature_7  Feature_8  Feature_9  Feature_10  ...  Feature_3229  \
0     0.757830  -0.722168   0.757830    0.038485  ...     -1.903318   
1    -0.768013   0.617284  -0.768013   -0.059407  ...     -0.133632   
2     0.689108  -0.672790   0.689108   -0.062952  ...     -0.972867   
3     1.599928  -1.272312   1.599928   -0.063502  ...     -0.486524   
4    -0.308667   0.138226  -0.308667   -0.058745  ...      0.680798   
..         ...        ...        ...         ...  ...           ...   
310   0.990873  -0.884254   0.990873   -0.060837  ...      0.202267   
311  -1.401877   1.297774  -1.401877   -0.060507  ...     -1.901386   
312   0.043164  -0.169541   0.043164   -0.058273  ...      0.271247   
313   0.814087  -0.762044   0.814087   -0.061786  ...     -1.381913   
314   1.083367  -0.946384   1.083367   -0.058583  ...      0.538947   

     Feature_3230  Feature_3231  Feature_3232  Feature_3233  Feature_3234  \
0       -1.903318     -0.795461           0.0     -0.386250     -1.156615   
1       -0.133632     -0.683039           0.0     -0.309647     -0.493571   
2       -0.972867     -0.396858           0.0     -0.308825     -0.995803   
3       -0.486524      0.283390           0.0     -0.154057     -0.763600   
4        0.680798      0.173152           0.0      0.084921      0.703383   
..            ...           ...           ...           ...           ...   
310      0.202267      0.498488           0.0     -0.027807     -0.355315   
311     -1.901386     -1.207844           0.0     -0.440121     -0.957524   
312      0.271247      0.120722           0.0     -0.091668     -0.222419   
313     -1.381913     -0.550115           0.0     -0.323534     -0.894995   
314      0.538947      0.687035           0.0      0.134792      0.163421   

     Feature_3235  Feature_3236  Feature_3237  Feature_3238  
0             0.0     -0.208265      1.487482     -1.156615  
1             0.0     -0.337385      0.542650     -0.493571  
2             0.0     -0.354606      1.137855     -0.995803  
3             0.0     -0.374634      0.852824     -0.763600  
4             0.0      0.196797     -0.859371      0.703383  
..            ...           ...           ...           ...  
310           0.0      0.162030      0.397758     -0.355315  
311           0.0      0.652483      1.190021     -0.957524  
312           0.0     -0.963045      0.088390     -0.222419  
313           0.0      0.392094      1.023034     -0.894995  
314           0.0      0.689963     -0.104044      0.163421  

[315 rows x 3238 columns]

In [73]:
feature_columns = X.columns

In [81]:
from sklearn.feature_selection import VarianceThreshold

selector = VarianceThreshold(threshold=1e-5)
X_var = selector.fit_transform(X_scaled_df)

print(f"Reduced from {X_scaled_df.shape[1]} to {X_var.shape[1]} features")

selected_mask = selector.get_support()

selected_features = [feature_columns[i] for i in range(len(selected_mask)) if selected_mask[i]]

Reduced from 3238 to 3123 features


In [129]:
from sklearn.feature_selection import SelectKBest, f_classif

selector = SelectKBest(score_func=f_classif, k=10)  # Try k=100 to start

X_kbest = selector.fit_transform(X_var, y)

# You can also get the selected column names if needed
selected_mask = selector.get_support()

selected_k_features = [selected_features[i] for i in range(len(selected_mask)) if selected_mask[i]]

In [130]:
X_kbest_df = pd.DataFrame(X_kbest, columns=selected_k_features)

In [21]:
# Convert back to DataFrame for inspection
X_var_df = pd.DataFrame(X_var)

# Correlation matrix
corr_matrix = X_var_df.corr().abs()

# Upper triangle of correlation matrix
upper = corr_matrix.where(np.triu(np.ones(corr_matrix.shape), k=1).astype(bool))

# Find columns with correlation > 0.95
to_drop = [column for column in upper.columns if any(upper[column] > 0.95)]

# Drop them
X_uncorrelated = X_var_df.drop(columns=to_drop)

print(f"Dropped {len(to_drop)} correlated features. Remaining: {X_uncorrelated.shape[1]}")


Dropped 2402 correlated features. Remaining: 721


In [45]:
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(n_estimators=100, random_state=42)
rf.fit(X_uncorrelated, y)  # y = your target column (CLASS)

importances = rf.feature_importances_
indices = np.argsort(importances)[::-1][:100]  # Keep top 100

X_selected = X_uncorrelated.iloc[:, indices]

In [ ]:
from sklearn.model_selection import StratifiedKFold

cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)


In [131]:
from sklearn.model_selection import train_test_split

X_train, X_val, y_train, y_val = train_test_split(X_kbest_df, y, test_size=0.2, random_state=42, stratify=y)

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.metrics import accuracy_score

# Instantiate logistic regression model
clf_lr = LogisticRegression(max_iter=1000, class_weight="balanced", random_state=42, C=1)

# Fit the model
clf_lr.fit(X_train, y_train)

# Predict on validation set
y_pred = clf_lr.predict(X_val)

accuracy_logistic_regression = accuracy_score(y_val, y_pred)

In [ ]:
print(confusion_matrix(y_val, y_pred))
print(classification_report(y_val, y_pred))
print(accuracy_logistic_regression)

[[27 11]
 [15 10]]
              precision    recall  f1-score   support

           0       0.64      0.71      0.68        38
           1       0.48      0.40      0.43        25

    accuracy                           0.59        63
   macro avg       0.56      0.56      0.55        63
weighted avg       0.58      0.59      0.58        63



In [132]:
from sklearn.model_selection import GridSearchCV

param_grid = {'C': [0.01, 0.1, 1, 10, 100]}
clf = LogisticRegression(max_iter=10000, random_state=42)

grid_search = GridSearchCV(clf, param_grid, cv=5, scoring='f1_macro')
grid_search.fit(X_train, y_train)

print("Best C:", grid_search.best_params_)

Best C: {'C': 1}


In [100]:
from sklearn.ensemble import RandomForestClassifier

clf_rf = RandomForestClassifier(n_estimators=1000, class_weight='balanced', random_state=42)
clf_rf.fit(X_train, y_train)

y_pred_rf = clf_rf.predict(X_val)
print(confusion_matrix(y_val, y_pred_rf))
print(classification_report(y_val, y_pred_rf))


[[28 10]
 [17  8]]
              precision    recall  f1-score   support

           0       0.62      0.74      0.67        38
           1       0.44      0.32      0.37        25

    accuracy                           0.57        63
   macro avg       0.53      0.53      0.52        63
weighted avg       0.55      0.57      0.55        63



In [37]:
from xgboost import XGBClassifier

xgb_clf = XGBClassifier(n_estimators=100, scale_pos_weight=1.5, use_label_encoder=False, eval_metric='logloss', random_state=42)
xgb_clf.fit(X_train_scaled, y_train)
y_pred_xgb = xgb_clf.predict(X_val_scaled)

print(confusion_matrix(y_val, y_pred_xgb))
print(classification_report(y_val, y_pred_xgb))


d:\classifier-algorithms\.venv\Lib\site-packages\xgboost\training.py:183: UserWarning: [15:39:27] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:738: 
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)


[[25 13]
 [18  7]]
              precision    recall  f1-score   support

           0       0.58      0.66      0.62        38
           1       0.35      0.28      0.31        25

    accuracy                           0.51        63
   macro avg       0.47      0.47      0.46        63
weighted avg       0.49      0.51      0.50        63

